PROJECT_DIR = /usr/home/potato/sketchbook/

ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

USER_LIB_PATH = /home/potato/sketchbook/
BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk
